# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EquipmentSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentslot',
            name='slot_duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='equipmentslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 16, 4, 51, 163000, tzinfo=utc), verbose_name='start time'),
        ),
    ]
