# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EquipmentSchedule', '0003_auto_20170803_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentslot',
            name='opperator',
            field=models.CharField(default='anonymous', max_length=128),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 17, 24, 59, 832000, tzinfo=utc), verbose_name='start time'),
        ),
    ]
