# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EquipmentSchedule', '0004_auto_20170910_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 1, 27, 37, 639000, tzinfo=utc), verbose_name='start time'),
        ),
    ]
