# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EquipmentSchedule', '0005_auto_20170910_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourallowance', models.IntegerField()),
                ('hourtotal', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 2, 25, 17, 406000, tzinfo=utc), verbose_name='start time'),
        ),
    ]
